#!/bin/bash
# Script para fazer deploy no Railway

echo "🚀 Deploy Instructions for Railway"
echo "=================================="
echo ""
echo "1. Create GitHub repository at https://github.com/new"
echo "   - Repo name: aura-bot (or whatever you prefer)"
echo "   - Description: Bot de apostas e filas para Discord"
echo "   - Do NOT initialize with README, .gitignore, or license"
echo ""
echo "2. Run these commands in this directory:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Railway:"
echo "   a) Go to https://railway.app"
echo "   b) Sign up with GitHub"
echo "   c) Create new project → Deploy from GitHub repo"
echo "   d) Select this repository (aura-bot)"
echo "   e) Railway will detect Docker configuration automatically"
echo ""
echo "4. Add environment variables in Railway dashboard:"
echo "   DISCORD_TOKEN=your_discord_bot_token_here"
echo "   MONGO_URI=your_mongodb_connection_string_here"
echo "   PORT=4000"
echo ""
echo "5. Deploy and monitor logs in Railway dashboard"
echo "=================================="
